env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:jest/recommended'
  - 'plugin:prettier/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - 'jest'
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  arrow-parens:
    - error
    - always
  no-unused-vars:
    - error
  no-unused-labels:
    - error
  no-unused-expressions:
    - error
  camelcase:
    - error
  no-console:
    - error
  space-before-blocks:
    - error
    - always

ignorePatterns:
  - '*.config.js'
  - '*.json'
